### ISSUE TITLE
您好，请问vovnet上24e您训练需要多久呢？

### ISSUE THREAD

**Issue by loserhou** [AlmoonYsl/OPEN#2]

**Comment by loserhou** [comment]
可以发我一份vovnet上训练24e的log吗，万分感谢

**Comment by AlmoonYsl** [comment]
@loserhou 
您好，V2-99 800x320分辨率训练24epoch大概需要12h。
由于V2-99 800x320分辨率24epoch的实验比较久了，现在只有提交test的V2-99 1600x640分辨率60epoch的log，如果您需要的话，我可以发给您。

**Comment by loserhou** [comment]
> @loserhou 您好，V2-99 800x320分辨率训练24epoch大概需要12h。 由于V2-99 800x320分辨率24epoch的实验比较久了，现在只有提交test的V2-99 1600x640分辨率60epoch的log，如果您需要的话，我可以发给您。

好的，我邮箱是hyfjay@163.com，另外，为什么我在四张A800上需要训练十七小时左右，bs也是16

**Comment by AlmoonYsl** [comment]
@loserhou 
您可以试试8卡的设置，4卡的训练时间可能不同。log已通过邮箱发送。

**Comment by loserhou** [comment]
> @loserhou 您可以试试8卡的设置，4卡的训练时间可能不同。log已通过邮箱发送。

感谢，祝科研顺利
