### ISSUE TITLE
关于训练Lossa

### ISSUE THREAD

**Issue by loserhou** [AlmoonYsl/OPEN#3]
<img width="180" alt="fbd4eca686212e1c64fff15f679cdd2" src="https://github.com/user-attachments/assets/66284e70-0c0e-4a0e-8027-d23fd55f0946">
<img width="353" alt="070ba5182cafa3a0cc12fe08e603cf6" src="https://github.com/user-attachments/assets/9a3bbf59-830c-447d-a507-7793982b10bb">
我的训练结果和您提供的log相比好像多出了一项，请问这是正确的吗？

**Comment by loserhou** [comment]
<img width="392" alt="c83efd7c36daacd301bc8bc5b0ec782" src="https://github.com/user-attachments/assets/334410ef-0d2d-4fd9-9860-9f55dc034d09">
<img width="514" alt="6bd49ca70bfdaeee9162f93b1a48291" src="https://github.com/user-attachments/assets/22fa0153-1710-485b-a055-5f15e16369fa">
有两项loss很大，是哪里有问题吗

**Comment by AlmoonYsl** [comment]
@loserhou 
您好，loss的名称是有修改过的。我已发送了开源代码训练后的R50 704分辨率的log给您，您可以参考下这个。

**Comment by AlmoonYsl** [comment]
> <img alt="c83efd7c36daacd301bc8bc5b0ec782" width="392" src="https://private-user-images.githubusercontent.com/151776629/382346538-334410ef-0d2d-4fd9-9860-9f55dc034d09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTYyMzcsIm5iZiI6MTczMDUxNTkzNywicGF0aCI6Ii8xNTE3NzY2MjkvMzgyMzQ2NTM4LTMzNDQxMGVmLTBkMmQtNGZkOS05ODYwLTlmNTVkYzAzNGQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwMjUyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGU0ZjZiZWI2OGIyNzBhMzBlYTM4YjdiZjVmYmUxMzA4YWYwOTM1NDlhMjcxMzNiZTRlMDE0NmQ0ZDlmNGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4w1ofOpqw7v0QLrufI4g0SHS2uWu2eHWSdtWCxRc_dQ"> <img alt="6bd49ca70bfdaeee9162f93b1a48291" width="514" src="https://private-user-images.githubusercontent.com/151776629/382346556-22fa0153-1710-485b-a055-5f15e16369fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTYyMzcsIm5iZiI6MTczMDUxNTkzNywicGF0aCI6Ii8xNTE3NzY2MjkvMzgyMzQ2NTU2LTIyZmEwMTUzLTE3MTAtNDg1Yi1hMDU1LTVmMTVlMTYzNjlmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwMjUyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWZiNDMwMmVkOTJlYTAyZjFiNWFkYWU0ZmY0NDhmYTY1YmM2MDNmNzBlNWQzY2RmN2NlODg5YWE3ZjM0YTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b1uaJUyXndKDNoB7e_Y3rmVaZw1apZf3nRA4rbd-R1g"> 有两项loss很大，是哪里有问题吗

发给您的V2-99的log是1600x640分辨率的，因此和800x320分辨率的loss可能不一致。

**Comment by loserhou** [comment]
> @loserhou 
> 您好，loss的名称是有修改过的。我已发送了开源代码训练后的R50 704分辨率的log给您，您可以参考下这个。

感谢
