### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by cnctdadots** [AlmoonYsl/OPEN#4]
Thank you for great work on this paper. 
I am interested to try OPEN, but I couldn't find any installation instruction. 
any plans to release that, please?

Thank you again!

**Comment by AlmoonYsl** [comment]
@cnctdadots Hi,
You can refer to these commands for preparing environment.
```
Python >= 3.8
CUDA == 10.2 or 11.1
PyTorch == 1.9.0
mmdet3d == 1.0.0rc6

pip install mmcv-full==1.6.0
pip install mmdet==2.28.2
pip install mmsegmentation==0.30.0
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v1.0.0rc6 
pip install -e .

```
